#Databaseconfiguration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/securitydb
    password: '1000239'
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create

jwt:
  secret:
    key: b8bdbf81d4319886d639601135d8d6d2514a0bc3c4859e82dd7245c317e2a612
  time:
    expiration: 86400000